"""Corrigindo migração pendente

Revision ID: 1641e4150847
Revises: 4fc8f67c2862
Create Date: 2025-02-20 23:12:25.120884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1641e4150847'
down_revision = '4fc8f67c2862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condicionante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licenca_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prazo_cumprimento', sa.String(length=100), nullable=True),
    sa.Column('meta_execucao', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['licenca_id'], ['licenca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.drop_column('condicionantes')
        batch_op.drop_column('status')
        batch_op.drop_column('prazo_cumprimento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo_cumprimento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('condicionantes', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('condicionante')
    # ### end Alembic commands ###
