"""Adicionando ondelete CASCADE na Condicionante

Revision ID: 16a5a8507b48
Revises: cfb5d97ad4d6
Create Date: 2025-02-23 21:28:01.408385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a5a8507b48'
down_revision = 'cfb5d97ad4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condicionante', schema=None) as batch_op:
        batch_op.alter_column('situacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint('condicionante_licenca_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'licenca', ['licenca_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condicionante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('condicionante_licenca_id_fkey', 'licenca', ['licenca_id'], ['id'])
        batch_op.alter_column('situacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
