"""Inicializando banco

Revision ID: 44d4d485c651
Revises: 
Create Date: 2025-02-18 23:48:25.869058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d4d485c651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=False),
    sa.Column('ato', sa.String(length=200), nullable=False),
    sa.Column('portaria', sa.String(length=50), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('condicionantes', sa.Text(), nullable=True),
    sa.Column('prazo_cumprimento', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('licenca')
    # ### end Alembic commands ###
