"""Corrigindo erro de tabela existente

Revision ID: 69c00c635ac1
Revises: 4fc8f67c2862
Create Date: 2025-02-21 02:07:43.259964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c00c635ac1'
down_revision = '4fc8f67c2862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condicionante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_execucao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('situacao', sa.String(length=50), nullable=True))
        batch_op.alter_column('prazo_cumprimento',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('condicionante', schema=None) as batch_op:
        batch_op.alter_column('prazo_cumprimento',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('situacao')
        batch_op.drop_column('meta_execucao')

    # ### end Alembic commands ###
