"""Corrigindo relacionamento Licenca-Condicionante

Revision ID: b5a9bbfab532
Revises: 16a5a8507b48
Create Date: 2025-02-23 21:31:38.390661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a9bbfab532'
down_revision = '16a5a8507b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.alter_column('empresa',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('email_empresa',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ato',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('portaria',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('portaria',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('ato',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('email_empresa',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('empresa',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
